project:
  type: website

website:
  title: "jabers-blog-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jabertuhin
      - icon: twitter
        href: https://twitter.com/jabertuhin
format:
  html:
    theme: morph
    css: styles.css
