project:
  type: website

website:
  title: "Jaber's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jabertuhin
      - icon: twitter
        href: https://twitter.com/jabertuhin
format:
  html:
    theme: lux
    css: styles.css
    smooth-scroll: true    
    title-block-banner: true

comments: false
